account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('profile/scrap/<int:user_id>/', views.ProfileVoteListView.as_view(template_name='wyw/profile_scrap.html'), name='profile_scrap'),
    path('profile/', views.profile, name='profile'),
    path('follow/<int:user_id>/', views.follow, name='follow'),
    path('serializers/userpost', views.UserPost.as_view()),
    path('serializers/userpost/<int:pk>/', views.UserDetailPost.as_view()),
    path('serializers/profilepost', views.ProfilePost.as_view()),
    path('serializers/profilepost/<int:pk>/', views.ProfileDetailPost.as_view()),


]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from wyw.views import base_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('whatyourweb/',include('wyw.urls')),
    path('account/',include('account.urls'),),
    path('',base_views.index, name='index'),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wyw/urls.py
from email.mime import base
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import base_views, posting_views, comment_views

app_name = 'wyw'

urlpatterns = [
     path('profile/', base_views.profile, name='profile'),
    # path('',base_views.index, name='index'),
    # path('<int:posting_id>/', base_views.detail, name='detail'),
    # path('comment/create/<int:posting_id>/', posting_views.comment_create , name='comment_create'),
    # path('posting/create', posting_views.posting_create, name='posting_create'),
    # path('posting/modify/<int:posting_id>/', posting_views.posting_modify, name='posting_modify'),
    # path('posting/delete/<int:posting_id>/', comment_views.posting_delete, name='posting_delete'),
    # path('comment/modify/<int:comment_id>/', comment_views.comment_modify, name='comment_modify'),
    # path('comment/delete/<int:comment_id>/', comment_views.comment_delete, name='comment_delete'),
        # base_views.py
#     path('',
#          base_views.index, name='index'),
     path('posting/list/', base_views.index, name='index'),
    path('posting/list/<str:category_name>/', base_views.index, name='index'),

    path('posting/detail/<int:posting_id>/',
         base_views.detail, name='detail'),

    # question_views.py
     # path('posting/create/',
     #     posting_views.posting_create, name='posting_create'),
    path('posting/create/<str:category_name>/',
         posting_views.posting_create, name='posting_create'),
    path('posting/modify/<int:posting_id>/',
         posting_views.posting_modify, name='posting_modify'),
    path('posting/delete/<int:posting_id>/',
         posting_views.posting_delete, name='posting_delete'),
     # path('posting/craete/<str:category_name>/', posting_views.posting_create, name='posting_create'),


    # answer_views.py
    path('comment/create/<int:posting_id>/',
         comment_views.comment_create, name='comment_create'),
    path('comment/modify/<int:comment_id>/',
         comment_views.comment_modify, name='comment_modify'),
    path('comment/delete/<int:comment_id>/',
         comment_views.comment_delete, name='comment_delete'),

    path('posting/vote/<int:posting_id>/', posting_views.posting_vote, name='posting_vote'),
    path('posting/scrap/<int:posting_id>/', posting_views.posting_scrap, name='posting_scrap'),
     path('ranking/', base_views.ranking, name='ranking'),
     path('recommend/', base_views.recommend, name='recommend'),

    path('serializers/categorypost', base_views.CategoryPost.as_view()),
    path('serializers/categorypost/<int:pk>/', base_views.CategoryPost.as_view()),
    path('serializers/postingpost', base_views.PostingPost.as_view()),
    path('serializers/postingpost/<int:pk>/', base_views.PostingDetailPost.as_view()),
    path('serializers/commentpost', base_views.CommentPost.as_view()),
    path('serializers/commentpost/<int:pk>/', base_views.CommentDetailPost.as_view()),

     
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wyw/models.py
from django.db import models
from account.models import User
from django.urls import reverse
from account.models import Profile

class Category(models.Model):
    name = models.CharField(max_length=20, unique=True)
    description = models.CharField(max_length=200, null=True, blank=True)
    has_comment = models.BooleanField(default=True)  # 답변가능 여부

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('wyw:index', args=[self.name])
    


class Posting(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    author_avatar = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='author_question')
    modify_date = models.DateTimeField(null=True, blank=True)
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    voter = models.ManyToManyField(User, related_name='voter_question')  # 추천인 추가
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category_posting')
    scraper = models.ManyToManyField(User, related_name='scrap_posting')  # through는 연결할 모델을 의미한다.
    scrap_counter = models.IntegerField(default=0)  # 불필요한 연산 없이 진행하기 위해.
    logo = models.URLField(max_length=200)



    def __str___(self):
        return self.subject

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    modify_date = models.DateTimeField(null=True, blank=True)
    Posting = models.ForeignKey(Posting, on_delete=models.CASCADE)
    score = models.IntegerField(default=0)
    content = models.TextField()
    create_date = models.DateTimeField()

wyw/views/base_views.py
from unicodedata import category, name
from django.core.paginator import Paginator
from django.db.models import Q, Count
from django.shortcuts import get_object_or_404, render, render, redirect
from django.contrib.auth.decorators import login_required

from ..forms import CommentForm
from ..models import Posting # 부모 디렉토리
from ..models import Comment
from ..models import Category
from account.models import User
from django.db.models import Avg
from ..serializers import CategorySerializer
from ..serializers import PostingSerializer
from ..serializers import CommentSerializer
from rest_framework import generics

class CategoryPost(generics.ListCreateAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer

class CategoryDetailPost(generics.RetrieveUpdateDestroyAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer

class PostingPost(generics.ListCreateAPIView):
    queryset = Posting.objects.all()
    serializer_class = PostingSerializer

class PostingDetailPost(generics.RetrieveUpdateDestroyAPIView):
    queryset = Posting.objects.all()
    serializer_class = PostingSerializer

class CommentPost(generics.ListCreateAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer

class CommentDetailPost(generics.RetrieveUpdateDestroyAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer


def index(request, category_name='backend'):
    category = Category.objects.get(name=category_name)
    """
    게시글 목록 출력
    """

    # 입력 인자
    page = request.GET.get('page','1')
    kw = request.GET.get('kw', '')  # 검색어
    so = request.GET.get('so', 'recommend')  # 정렬기준
    cat = request.GET.get('category')  # 정렬기준


    category_list = Category.objects.all()
    category = get_object_or_404(Category, name=category_name)

    # # 조회
    posting_list = Posting.objects.filter(category=category)



            # 정렬
    if so == 'recommend':
        posting_list = Posting.objects.filter(category=category).annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        posting_list = Posting.objects.filter(category=category).annotate(num_comment=Count('comment')).order_by('-num_comment', '-create_date')
    else:  # recent
        posting_list = Posting.objects.filter(category=category).order_by('-create_date')

    if kw:
        posting_list = posting_list.filter(
            Q(subject__icontains=kw) |  # 제목검색
            Q(content__icontains=kw) |  # 내용검색
            Q(author__name__icontains=kw) |  # 질문 글쓴이검색
            Q(comment__author__name__icontains=kw)  # 답글 글쓴이검색
        ).distinct()


    # 페이징 처리
    paginator = Paginator(posting_list, 10) # 페이지당 10개씩 보여 주기
    page_obj = paginator.get_page(page)


    context = {'posting_list' : page_obj, 'page':page, 'kw':kw,'category_list':category_list,'category':category, 'so':so, 'user':request.user}
    return render(request, 'wyw/posting_list.html', context)

def detail(request, posting_id):
    """
    Posting 내용 출력
    """
    posting = get_object_or_404(Posting, pk=posting_id)
    ratings = Comment.objects.filter(Posting=posting)
    rated = 1
    
    for rating in ratings:
        if request.user == rating.author:
            rated = rating
    rating_form = CommentForm()

    sum = Comment.objects.filter(Posting=posting).aggregate(Avg('score'))
    if sum['score__avg']:
        avg_score = round(sum['score__avg'],2)
    else:
        avg_score = 0

    posting.user_Rating = avg_score
    posting.save()

    context = {'posting':posting,'rating_form':rating_form, 'avg_score':avg_score }
    return render(request, 'wyw/posting_detail.html', context)

def profile(request):
    context = {'user': request.user}
    return render(request, 'wyw/profile.html', context)

def ranking(request):
    user_list = User.objects.all().order_by('-followers')
    return render(request, 'wyw/ranking.html', {'allUser':user_list})

@login_required(login_url='account:login')
def recommend(request):
    category = Category.objects.all()
    # fav1 = request.user.favorites_1
    # fav2 = request.user.favorites_2
    category_list_1 = Category.objects.filter(description__startswith = request.user.favorites_1)
    category_list_2 = Category.objects.filter(description__startswith = request.user.favorites_2)

    posting_list_1 = Posting.objects.filter(category__in = category_list_1)
    posting_list_2 = Posting.objects.filter(category__in = category_list_2)
    posting_list_1 = posting_list_1.annotate(num_voter=Count('voter')).order_by('-num_voter')
    posting_list_2 = posting_list_2.annotate(num_voter=Count('voter')).order_by('-num_voter')


    all_list = [posting_list_1, posting_list_2]




    category_list = Category.objects.all()

    context = {'posting_list_1':posting_list_1, 'posting_list_2':posting_list_2, 'category_list':category_list, 'category':category, 'user': request.user, 'all_list' : all_list}

    return render(request, 'wyw/recommend_site.html',context)

wyw/views/comment_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, render, redirect
from django.utils import timezone
from django.db.models import Q


from ..forms import CommentForm
from ..models import Posting, Comment

@login_required(login_url='common:login')
def comment_create(request, posting_id):
    """
    댓글 등록
    """

    posting = get_object_or_404(Posting, pk=posting_id)
    # comment_list = Comment.objects.filter(Comment, posting_id = posting.pk)
    comment_list = Comment.objects.filter(Q(Posting = posting) & Q(author = request.user) )


    if (comment_list):
        messages.error(request, '이미 댓글을 작성하셨습니다.')
        return redirect('wyw:detail', posting_id=posting_id)

    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user # author 속성에 로그인 계정 저장
        comment.create_date = timezone.now()
        comment.Posting = posting
        comment.save()
        return redirect('wyw:detail', posting_id=posting.id)
    else:
        form = CommentForm()
    context = {'posting':posting, 'form':form}
    return render(request,'wyw/posting_detail.html', context)

@login_required(login_url='common:login')
def comment_modify(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('wyw:detail', posting_id=comment.Posting.id)
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('wyw:detail', posting_id=comment.Posting.id)
    else:
        form = CommentForm(instance=comment)
    context = {'comment': comment, 'form': form}
    return render(request, 'wyw/comment_form.html', context)

@login_required(login_url='common:login')
def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        comment.delete()
    return redirect('wyw:detail', posting_id=comment.Posting.id)

wyw/views/posting_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, render, redirect
from django.utils import timezone

from ..forms import PostingForm
from ..models import Posting, Category, Comment
from selenium import webdriver
from bs4 import BeautifulSoup
import time
import dload
import os
import requests

@login_required(login_url='account:login')
def posting_create(request, category_name):
    category = Category.objects.get(name=category_name)
    if request.method == 'POST':
        form = PostingForm(request.POST)
        if form.is_valid():
            posting = form.save(commit=False)
            posting.author = request.user # author 속성에 로그인 계정 저장
            posting.author_avatar = request.user.profile
            posting.create_date = timezone.now()

            posting.category = category

            response = requests.get(request.POST.get("logo", ""))

            if response.status_code == 200:
                html = response.text
                soup = BeautifulSoup(html, 'html.parser')
                image = soup.select_one('meta[property="og:image"]')['content']




            posting.logo = image
# 크롬에서 가져오고 싶은 이미지 오른쪽 클릭
# 검사 -> 개발자 도구에서의 선택된 부분을 오린쪽 클릭
# copy -> copy selector 를 하여 복사된 정보에서 중복을 삭제
 
            # src = thumbnails["content"]    # 가져온 태그 정보중에 src만 가져옴
            # posting.logo = dload.save(image, f'C:\Django\whatyourweb\wyw\images/333.jpg')    # 설정한 경로로 jpg파일로 다운로드
            # driver.quit() # 끝나면 닫아주기
            # path='C:\Django\whatyourweb\wyw\images'
            # img_list = os.listdir(path)
            # posting.logo = img_list
            posting.save()
            return redirect('wyw:detail', posting_id=posting.id)
    else:
        form = PostingForm()

    context = {'form': form, 'category': category,}
    return render(request, 'wyw/posting_form.html', context)

@login_required(login_url='account:login')
def posting_modify(request, posting_id):
    posting = get_object_or_404(Posting, pk=posting_id)
    if request.user != posting.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('wyw:detail', posting_id=posting.id)
    if request.method == "POST":
        form = PostingForm(request.POST, instance=posting)
        if form.is_valid():
            posting = form.save(commit=False)
            posting.modify_date = timezone.now()  # 수정일시 저장
            response = requests.get(request.POST.get("logo", ""))

            if response.status_code == 200:
                html = response.text
                soup = BeautifulSoup(html, 'html.parser')
                image = soup.select_one('meta[property="og:image"]')['content']




            posting.logo = image

            posting.save()
            return redirect('wyw:detail', posting_id=posting.id)
    else:
        form = PostingForm(instance=posting)
    context = {'form': form}
    return render(request, 'wyw/posting_form.html', context)

@login_required(login_url='account:login')
def posting_delete(request, posting_id):
    posting = get_object_or_404(Posting, pk=posting_id)
    if request.user != posting.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('wyw:detail', posting_id=posting.id)
    posting.delete()
    return redirect('wyw:index')

@login_required(login_url='account:login')
def posting_vote(request, posting_id):
    posting = get_object_or_404(Posting, pk=posting_id)
    if request.user == posting.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        posting.voter.add(request.user)
    return redirect('wyw:detail', posting_id=posting.id)

@login_required(login_url='account:login')
def posting_scrap(request, posting_id):
    posting = get_object_or_404(Posting, pk=posting_id)
    if posting.scraper.filter(id=request.user.id).exists():
        posting.scraper.remove(request.user)  # 이미 추가되어 있다면 삭제한다.
        posting.scrap_counter -= 1
        posting.save()  # save가 있어야 반영된다.
    else:
        posting.scraper.add(request.user)  # 포스팅의 likeUser에 user를 더한다.
        posting.scrap_counter += 1
        posting.save()
    return redirect('wyw:detail', posting_id=posting_id)

templates/wyw/comment_form.html
{% extends 'base.html' %}
{% block content %}
<!-- 답변 수정-->
<div class="container my-3">
    <form method="post">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="content" class="form-label">댓글내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/wyw/posting_detail.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="container my-3">
    <!-- message 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}
    <h2 class="border-bottom py-2">{{ posting.subject }}</h2>
    <img class="bd-placeholder-img rounded-circle" height=132 width=132 src="{{posting.logo}}" alt="">
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ posting.content| safe  }}</div>            <div class="d-flex justify-content-end">

                {% if posting.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">수정된 날짜</div>
                    <div>{{ posting.modify_date|date:'Y-m-d H' }}</div>
                </div>
                {% endif %}    
                <div class="badge badge-light p-2 text-start">
                    <div class="content-section">
                        <img class="bd-placeholder-img rounded-circle" height=132 width=132 src="{{ posting.author_avatar.avatar.url }}"/>
                    </div>                      
                    <h4><a href="{% url 'account:profile_scrap' posting.author.id %}" class="badge rounded-pill bg-danger" style="text-decoration:none">{{ posting.author.name }}</a></h4>
                    <div>{{ posting.create_date|date:'Y-m-d H' }}</div>

                </div>
            </div>
            <div class="my-3">
                <a href="javascript:void(0)" data-uri="{% url 'wyw:posting_vote' posting.id  %}"
                class="recommend btn btn-sm btn-outline-secondary"> 추천
                 <span class="badge rounded-pill bg-success">{{posting.voter.count}}</span>
             </a> 
             <a href="{% url 'wyw:posting_scrap' posting.id%}" class="btn btn-primary">보관함 담기</a>
             <div class="text-center">이 글을 보관함으로 가져간 사람 수:{{posting.scraper.count}}</div>
                <div class="text'center">이 글의 평점 {{avg_score}} 점</div>
                {% if request.user == posting.author %}
                <a href="{% url 'wyw:posting_modify' posting.id  %}" 
                   class="btn btn-sm btn-outline-secondary">수정</a>
                   <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                   data-uri="{% url 'wyw:posting_delete' posting.id  %}">삭제</a>            
                {% endif %}
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{posting.comment_set.count}}개의 댓글이 있습니다.</h5>
    {% for comment in posting.comment_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ comment.content }}</div>
            <div class="d-flex justify-content-end">
                {% if comment.modify_date|date:'Y-m-d H' %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">수정된 날짜</div>
                    <div>{{ comment.modify_date|date:'Y-m-d H' }}</div>
                </div>
                {% endif %}    
                <div class="badge badge-light p-2 text-start">
                    <div class="mb-2">{{ comment.author.name }}</div>
                    <div>{{ comment.create_date|date:'Y-m-d H' }}</div>
                    <div class="mb-2">평가한 평점</div>
                    <div>{{ comment.score }} 점</div>
                </div>
            </div>
            <div class="my-3">
                {% if request.user == comment.author %}
                <a href="{% url 'wyw:comment_modify' comment.id  %}" 
                   class="btn btn-sm btn-outline-secondary">수정</a>
                   <a href="#" class="delete btn btn-sm btn-outline-secondary "
                   data-uri="{% url 'wyw:comment_delete' comment.id  %}">삭제</a>    
                {% endif %}
            </div>    
            </div>    
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'wyw:comment_create' posting.id %}" method="post" class="my-3">
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
        {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
        {% endfor %}
        </div>
        {% endif %}
        <div class="form-group">
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
              name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <div class="mb-3">
            <label for="score" class="form-label">평점</label>
            <select name="score">
                <option value="1">1점</option>
                <option value="2">2점</option>
                <option value="3" selected="selected">3점</option>
                <option value="4">4점</option>
                <option value="5">5점</option>
            </select>
        </div>
        

            <input type="submit" value="댓글" class="btn btn-primary">
    </form>

</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
const recommend_elements = document.getElementsByClassName("recommend");
Array.from(recommend_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 추천하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
<style>
    #myform fieldset{
    display: inline-block; /* 하위 별점 이미지들이 있는 영역만 자리를 차지함.*/
    direction: rtl; /* 이모지 순서 반전 */
    border: 0; /* 필드셋 테두리 제거 */
}
#myform fieldset legend{
    text-align: left;
}
#myform input[type=radio]{
    display: none; /* 라디오박스 감춤 */
}
#myform label{
    font-size: 3em; /* 이모지 크기 */
    color: transparent; /* 기존 이모지 컬러 제거 */
    text-shadow: 0 0 0 #f0f0f0; /* 새 이모지 색상 부여 */
}
#myform label:hover{
    text-shadow: 0 0 0 #a00; /* 마우스 호버 */
}
#myform label:hover ~ label{
    text-shadow: 0 0 0 #a00; /* 마우스 호버 뒤에오는 이모지들 */
}
#myform input[type=radio]:checked ~ label{
    text-shadow: 0 0 0 #a00; /* 마우스 클릭 체크 */
}
</style>
{% endblock %}

templates/wyw/profile_scrap.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    
    <div class="row">
            
        <img class="bd-placeholder-img rounded-circle" height=132 width=132 src="{{ profile_user.profile.avatar.url }}"/>
<h4 class="border-bottom pb-2 my-3">{{ profile_user.name }}님의 보관함</h4>
<div>
    <div>
      팔로잉 : {{ profile_user.followings.count }} / 팔로워 : {{ profile_user.followers.count }}
    </div>
    <details>
        <summary>팔로잉 목록 보기</summary>
        {% if profile_user.followings.count >= 1 %}
        {% for following in profile_user.followings.all %}
        <p>{{ following.name }}</p>
        {% endfor %}
        {% else %}
        <p>팔로잉을 하고 있는 사람이 없습니다.</p>
        {% endif %}
     </details>
     <details>
        <summary>팔로워 목록 보기</summary>
        {% if profile_user.followers.count >= 1 %}
        {% for followers in profile_user.followers.all %}
            <p>{{ followers.name }}</p>
        {% endfor %}
        {% else %}
            <p>팔로워를 하고 있는 사람이 없습니다.</p>
        {% endif %}
     </details>
          
  
    {% if user != profile_user %}
      <div>
        <form action="{% url 'account:follow' profile_user.id %}" method='POST'>
          {% csrf_token %}
          {% if user in profile_user.followers.all %}
            <input type="submit" class="btn btn-outline-danger" value='팔로우 취소'>
          {% else %}
            <input type="submit" class="btn btn-outline-primary"  value='팔로우'>
          {% endif %}
        </form>
      </div>  
    {% endif %}
  </div>                      

<!-- <div id="profile_base">
        <p class="mb-4">{{ profile_user.name }}님의 의 보관함 내용입니다.</p>
</div> -->

<!-- 답변 표시 Start -->


<table class="table">
    <thead>
        <tr class="text-center thead-dark">
            <th>번호</th>
            <th>구분</th>
            <th>추천</th>
            <th style="width:50%">제목</th>
            <th>글쓴이</th>
            <th>작성일시</th>
        </tr>
    </thead>
    <tbody>
    {% if page_obj %}
    {% for object in page_obj %}
    <tr class="text-center">
        <td>{{ forloop.counter }}</td>
        <td>{{ object.category.description }}</td>
        <td>
            {% if object.voter.count > 0 %}
                <span class="badge badge-warning px-2 py-1">{{ object.voter.count }}</span>
            {% else %}
                <span class="badge badge-light px-2 py-1" style="color:#ccc;">0</span>
            {% endif %}
        </td>
        
        <td class="text-center">
            {% if object.subject %}
                <a href="{% url 'wyw:detail' object.id %}">{{ object.subject }}</a>
                <!-- <a href="{{ object.get_absolute_url }}">{{ object.subject }}</a> -->
            {% else %}
                <a href="{% url 'wyw:detail' object.id %}">{{ object.content }}</a>
            {% endif %}
        </td>
        <td>{{ object.author.name }}</td>
        <td>{{ object.create_date|date:'Y-m-d H' }}</td>
    </tr>
    {% endfor %}
    {% else %}
    <tr>
        <td colspan="3">보관함에 담긴 글이 없습니다.</td>
    </tr>
    {% endif %}
    </tbody>
</table>
</div>
</div>



<!-- 페이징처리 시작 -->

<form id="searchForm" method="get">
    <input type="hidden" id="page" name="page" value="{{ page }}">
{#    <input type="hidden" id="so" name="so" value="{{ so }}">#}
</form>
{% endblock %}

{% block script %}
<script type='text/javascript'>
    $(document).ready(function(){
        $(".page-link").on('click', function() {
            $("#page").val($(this).data("page"));
            $("#searchForm").submit();
        });
    });
</script>
{% endblock %}