account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('profile/scrap/<int:user_id>/', views.ProfileVoteListView.as_view(template_name='wyw/profile_scrap.html'), name='profile_scrap'),
    path('profile/', views.profile, name='profile'),
    path('follow/<int:user_id>/', views.follow, name='follow'),
    path('serializers/userpost', views.UserPost.as_view()),
    path('serializers/userpost/<int:pk>/', views.UserDetailPost.as_view()),
    path('serializers/profilepost', views.ProfilePost.as_view()),
    path('serializers/profilepost/<int:pk>/', views.ProfileDetailPost.as_view()),


]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from wyw.views import base_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('whatyourweb/',include('wyw.urls')),
    path('account/',include('account.urls'),),
    path('',base_views.index, name='index'),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wyw/urls.py
from email.mime import base
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import base_views, posting_views, comment_views

app_name = 'wyw'

urlpatterns = [
     path('profile/', base_views.profile, name='profile'),
    # path('',base_views.index, name='index'),
    # path('<int:posting_id>/', base_views.detail, name='detail'),
    # path('comment/create/<int:posting_id>/', posting_views.comment_create , name='comment_create'),
    # path('posting/create', posting_views.posting_create, name='posting_create'),
    # path('posting/modify/<int:posting_id>/', posting_views.posting_modify, name='posting_modify'),
    # path('posting/delete/<int:posting_id>/', comment_views.posting_delete, name='posting_delete'),
    # path('comment/modify/<int:comment_id>/', comment_views.comment_modify, name='comment_modify'),
    # path('comment/delete/<int:comment_id>/', comment_views.comment_delete, name='comment_delete'),
        # base_views.py
#     path('',
#          base_views.index, name='index'),
     path('posting/list/', base_views.index, name='index'),
    path('posting/list/<str:category_name>/', base_views.index, name='index'),

    path('posting/detail/<int:posting_id>/',
         base_views.detail, name='detail'),

    # question_views.py
     # path('posting/create/',
     #     posting_views.posting_create, name='posting_create'),
    path('posting/create/<str:category_name>/',
         posting_views.posting_create, name='posting_create'),
    path('posting/modify/<int:posting_id>/',
         posting_views.posting_modify, name='posting_modify'),
    path('posting/delete/<int:posting_id>/',
         posting_views.posting_delete, name='posting_delete'),
     # path('posting/craete/<str:category_name>/', posting_views.posting_create, name='posting_create'),


    # answer_views.py
    path('comment/create/<int:posting_id>/',
         comment_views.comment_create, name='comment_create'),
    path('comment/modify/<int:comment_id>/',
         comment_views.comment_modify, name='comment_modify'),
    path('comment/delete/<int:comment_id>/',
         comment_views.comment_delete, name='comment_delete'),

    path('posting/vote/<int:posting_id>/', posting_views.posting_vote, name='posting_vote'),
    path('posting/scrap/<int:posting_id>/', posting_views.posting_scrap, name='posting_scrap'),
     path('ranking/', base_views.ranking, name='ranking'),
     path('recommend/', base_views.recommend, name='recommend'),

    path('serializers/categorypost', base_views.CategoryPost.as_view()),
    path('serializers/categorypost/<int:pk>/', base_views.CategoryPost.as_view()),
    path('serializers/postingpost', base_views.PostingPost.as_view()),
    path('serializers/postingpost/<int:pk>/', base_views.PostingDetailPost.as_view()),
    path('serializers/commentpost', base_views.CommentPost.as_view()),
    path('serializers/commentpost/<int:pk>/', base_views.CommentDetailPost.as_view()),

     
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wyw/views/base_views.py
from unicodedata import category, name
from django.core.paginator import Paginator
from django.db.models import Q, Count
from django.shortcuts import get_object_or_404, render, render, redirect
from django.contrib.auth.decorators import login_required

from ..forms import CommentForm
from ..models import Posting # 부모 디렉토리
from ..models import Comment
from ..models import Category
from account.models import User
from django.db.models import Avg
from ..serializers import CategorySerializer
from ..serializers import PostingSerializer
from ..serializers import CommentSerializer
from rest_framework import generics

class CategoryPost(generics.ListCreateAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer

class CategoryDetailPost(generics.RetrieveUpdateDestroyAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer

class PostingPost(generics.ListCreateAPIView):
    queryset = Posting.objects.all()
    serializer_class = PostingSerializer

class PostingDetailPost(generics.RetrieveUpdateDestroyAPIView):
    queryset = Posting.objects.all()
    serializer_class = PostingSerializer

class CommentPost(generics.ListCreateAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer

class CommentDetailPost(generics.RetrieveUpdateDestroyAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer


def index(request, category_name='backend'):
    category = Category.objects.get(name=category_name)
    """
    게시글 목록 출력
    """

    # 입력 인자
    page = request.GET.get('page','1')
    kw = request.GET.get('kw', '')  # 검색어
    so = request.GET.get('so', 'recommend')  # 정렬기준
    cat = request.GET.get('category')  # 정렬기준


    category_list = Category.objects.all()
    category = get_object_or_404(Category, name=category_name)

    # # 조회
    posting_list = Posting.objects.filter(category=category)



            # 정렬
    if so == 'recommend':
        posting_list = Posting.objects.filter(category=category).annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        posting_list = Posting.objects.filter(category=category).annotate(num_comment=Count('comment')).order_by('-num_comment', '-create_date')
    else:  # recent
        posting_list = Posting.objects.filter(category=category).order_by('-create_date')

    if kw:
        posting_list = posting_list.filter(
            Q(subject__icontains=kw) |  # 제목검색
            Q(content__icontains=kw) |  # 내용검색
            Q(author__name__icontains=kw) |  # 질문 글쓴이검색
            Q(comment__author__name__icontains=kw)  # 답글 글쓴이검색
        ).distinct()


    # 페이징 처리
    paginator = Paginator(posting_list, 10) # 페이지당 10개씩 보여 주기
    page_obj = paginator.get_page(page)


    context = {'posting_list' : page_obj, 'page':page, 'kw':kw,'category_list':category_list,'category':category, 'so':so, 'user':request.user}
    return render(request, 'wyw/posting_list.html', context)

def detail(request, posting_id):
    """
    Posting 내용 출력
    """
    posting = get_object_or_404(Posting, pk=posting_id)
    ratings = Comment.objects.filter(Posting=posting)
    rated = 1
    
    for rating in ratings:
        if request.user == rating.author:
            rated = rating
    rating_form = CommentForm()

    sum = Comment.objects.filter(Posting=posting).aggregate(Avg('score'))
    if sum['score__avg']:
        avg_score = round(sum['score__avg'],2)
    else:
        avg_score = 0

    posting.user_Rating = avg_score
    posting.save()

    context = {'posting':posting,'rating_form':rating_form, 'avg_score':avg_score }
    return render(request, 'wyw/posting_detail.html', context)

def profile(request):
    context = {'user': request.user}
    return render(request, 'wyw/profile.html', context)

def ranking(request):
    user_list = User.objects.all().order_by('-followers')
    return render(request, 'wyw/ranking.html', {'allUser':user_list})

@login_required(login_url='account:login')
def recommend(request):
    category = Category.objects.all()
    # fav1 = request.user.favorites_1
    # fav2 = request.user.favorites_2
    category_list_1 = Category.objects.filter(description__startswith = request.user.favorites_1)
    category_list_2 = Category.objects.filter(description__startswith = request.user.favorites_2)

    posting_list_1 = Posting.objects.filter(category__in = category_list_1)
    posting_list_2 = Posting.objects.filter(category__in = category_list_2)
    posting_list_1 = posting_list_1.annotate(num_voter=Count('voter')).order_by('-num_voter')
    posting_list_2 = posting_list_2.annotate(num_voter=Count('voter')).order_by('-num_voter')


    all_list = [posting_list_1, posting_list_2]




    category_list = Category.objects.all()

    context = {'posting_list_1':posting_list_1, 'posting_list_2':posting_list_2, 'category_list':category_list, 'category':category, 'user': request.user, 'all_list' : all_list}

    return render(request, 'wyw/recommend_site.html',context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=edge"> -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- wyw CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <meta charset="UTF-8">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>
    <title>WhatYourWeb</title>
</head>
<body>
    {% include "navbar.html" %}
    <!-- 기본 템플릿 안에 삽입될 내용 START -->
    {% block content %}
    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 END -->
    <!-- jQuery JS -->
    <script src="{% static 'jquery-3.4.1.min.js' %}"></script>
    <!-- Bootstrap JS -->
    <script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
    <!-- 네이게이션 바 -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
        <a class="navbar-brand" href="{% url 'wyw:index' %}">What-Your-Web</a>
        <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse"
        data-target="#navbarNav" aria-controls="navbarNav">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'account:logout' %}">
                    {{ user.name }}님 환영합니다. (로그아웃)
                </a> <td>나의 관심있는 개발분야는 「{{ user.favorites_1 }}」, 「{{ user.favorites_2}}」</td>
                {% else %}
                <a class="nav-link" href="{% url 'account:login' %}">로그인</a>
                {% endif %}
            </li>
            
        </ul>
    </div>
    <!-- <div class="col-4" style="text-align:center;">
        <element class="h-auto">
        <div class="input-group">
            <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="btn_search">검색</button>
            </div>
        </div>
        </element>
    </div>
 -->
    </nav>
    <form id="searchForm" method="get" action="{% url 'index' %}">
        <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
        <input type="hidden" id="page" name="page" value="{{ page }}">
        <input type="hidden" id="so" name="so" value="{{ so }}">    
    </form>

    
    {% block script %}
    <!-- <script type='text/javascript'>
    const page_elements = document.getElementsByClassName("page-link");
    Array.from(page_elements).forEach(function(element) {
        element.addEventListener('click', function() {
            document.getElementById('page').value = this.dataset.page;
            document.getElementById('searchForm').submit();
        });
    });
    const btn_search = document.getElementById("btn_search");
    btn_search.addEventListener('click', function() {
        document.getElementById('kw').value = document.getElementById('search_kw').value;
        document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        document.getElementById('searchForm').submit();
    });
    </script> -->
    {% endblock %}
    